name: Auto Merge Ship PRs

on:
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    if: >
      github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update && sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "${ADMIN_TOKEN}" | gh auth login --with-token

      - name: Find and Merge PR
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          PR_JSON=$(gh pr list --search "is:open is:pr base:main" --json number,title)
          echo "Fetched PRs: $PR_JSON"

          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[] | select(.title | startswith("ship")) | .number' | head -n 1)

          if [ -n "$PR_NUMBER" ]; then
            echo "Merging PR #$PR_NUMBER"
            gh pr merge "$PR_NUMBER" --merge --auto
          else
            echo "No PR found with a title starting with 'ship'."
          fi
