name: Auto Merge Ship PRs

on:
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    if: > 
      github.event.check_suite.conclusion == 'success' &&
      startsWith(github.event.check_suite.pull_requests[0].title, 'ship')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update && sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "${ADMIN_TOKEN}" | gh auth login --with-token

      - name: Merge the PR
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --search "is:open is:pr base:main" --json number --jq '.[] | .number' | head -n 1)
          if [ -n "$PR_NUMBER" ]; then
            echo "Merging PR #$PR_NUMBER"
            gh pr merge "$PR_NUMBER" --merge --auto
          else
            echo "No PR found to merge."
