name: Auto Merge Ship PRs

on:
  status

jobs:
  auto-merge:
    if: >
      github.event.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update && sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "${ADMIN_TOKEN}" | gh auth login --with-token

      - name: Find and Merge PR
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          # Buscar PRs abiertos en base: main
          PR_JSON=$(gh pr list --search "is:open is:pr base:main" --json number,title)
          echo "Fetched PRs: $PR_JSON"

          # Filtrar por títulos que comiencen con 'ship'
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[] | select(.title | startswith("ship")) | .number' | head -n 1)

          if [ -z "$PR_NUMBER" ]; then
            echo "No se encontró ningún PR con título que comience con 'ship'."
            exit 1
          fi

          # Intentar hacer merge
          echo "Haciendo merge al PR #$PR_NUMBER"
          gh pr merge "$PR_NUMBER" --merge --auto || echo "Error al intentar hacer merge al PR #$PR_NUMBER."
